### PR TITLE
Adding github action for automated submission

### PR DESCRIPTION
**Pull request by louisgv**
Related #260 

### Description

I found that joule doesn't have the store submission pipeline automated yet. This PR creates a `Submit` workflow to automate the zip submission process to Chrome/Firefox/Edge stores automatically, using [bpp](https://browser.market/) . It is set to run manually from the github action tab with a `tag` input, but we can tweak it to be even more granular as needed! The only thing that is needed is to create is a `SUBMIT_KEYS` github repository secret.

The `SUBMIT_KEYS` secret is a json, with the schema defined [here](https://github.com/plasmo-corp/bpp/blob/v1/keys.schema.json).

Here's a sample key for every stores:

```json
{
  "$schema": "https://raw.githubusercontent.com/plasmo-corp/bpp/v1/keys.schema.json",
  "chrome": {
    "clientId": "123",
    "refreshToken": "789",
    "extId": "abcd"
  },
	"firefox": {
		"apiKey": "123",
		"apiSecret": "789",
		"extId": "abcd"
	},
	"edge": {
		"cookie": "123",
		"extId": "abcd"
	},
	"opera": {
		"sessionid": "123",
		"csrftoken": "789",
		"packageId": 0
	}
}

```

You can find instructions on how to get those keys in the schema, or if you use vscode, the schema should provide hint/intelisense when hovering over the json properties. If you need any help in setting up the keys, feel free to @ me! Otherwise if this doesn't seem necessary, feel free to close the PR :)

### How it works

1. Via the `tag` input, it downloads the release assets associated with that tag from github
2. Then, it uploads the `joule-{tag}.zip` file to each store. For chrome it uses the webstore API. For firefox, it uses sign-addon (https://github.com/mozilla/sign-addon). For Opera and Edge, it uses Puppeteer to run a headless chrome instance to upload the zip files.

### Steps to Test

1. Fork this PR, and setup some test store items
2. Go to github action tab
3. Run the action manually with the latest tag

### CODE REVIEW

**Comment by wbobeirne** [comment]
Hey @louisgv, thanks for the contribution. While this all looks really convenient, it looks like your `bpp` action is relying on a closed source module to do the heavy lifting: https://www.npmjs.com/package/@plasmo-corp/bms. Given the security-conscious nature of Joule and its all site permissions as an extension, I'm not willing to hand over publishing credentials to any closed source software that I don't have to.

**Comment by louisgv** [comment]
Hi @wbobeirne, I was working on the documentation for the dependencies and thus was not ready to release the source yesterday. Just finalized that work and released the source for bms as well as its store-specific libraries:

- [Browser Market Submit](https://github.com/plasmo-corp/bms)
- [Mozilla Webstore Upload](https://www.npmjs.com/package/@plasmo-corp/mwu)
- [Chrome Webstore Upload](https://www.npmjs.com/package/@plasmo-corp/cwu)

I would love to have your audit of the source code for those modules :D

**Comment by wbobeirne** [comment]
Glad to hear it! Looks like bms is still private though, 404s for me. The other two have source available though.

**Comment by louisgv** [comment]
> Glad to hear it! Looks like bms is still private though, 404s for me. The other two have source available though.

Oopsie, I forgot to double check in incognito. It should be public now.

**Pull request closed without merging**
